// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using MvvmCross.Binding.BindingContext;
using MvvmCross.Platforms.Ios.Binding.Views;
using MvvmCross.Platforms.Ios.Presenters.Attributes;
using MvvmCross.Platforms.Ios.Views;
using UIKit;

namespace TodoApp.iOS.Views
{
	[MvxFromStoryboard]
	[MvxChildPresentation]
	public partial class ListInfoView : MvxTableViewController
	{
		public ListInfoView(IntPtr handle)
			: base(handle)
		{
		}

		public override void ViewDidLoad()
		{
			base.ViewDidLoad();

			this.Title = "Todo List Info";

			UpdateDescriptionStyle();

			var save = new UIBarButtonItem(UIBarButtonSystemItem.Save);
			var options = new UIBarButtonItem(UIImage.FromBundle("ic_more"), UIBarButtonItemStyle.Done, null);

			this.NavigationItem.RightBarButtonItems = new UIBarButtonItem[] { options, save };

			var source = new MvxStandardTableViewSource(this.TableView, "TitleText Title;");
			TableView.Source = source;

			var set = this.CreateBindingSet<ListInfoView, ViewModels.ListInfoViewModel>();
			set.Bind(NavigationItem)
			   .For(x => x.Title)
			   .To(vm => vm.Title);
			set.Bind(source)
			   .For(x => x.ItemsSource)
			   .To(vm => vm.Items);
			set.Bind(TitleTextField)
			   .To(vm => vm.ListTitle);
			set.Bind(DescrptionTextView)
			   .To(vm => vm.ListDescription);
			set.Bind(AddButton)
			   .To(vm => vm.AddNewItem);
			set.Bind(save)
			   .To(vm => vm.SaveList);
			set.Bind(options)
			   .To(vm => vm.ShowOptions);
			set.Apply();
		}

		private void UpdateDescriptionStyle()
		{
			DescrptionTextView.Layer.BackgroundColor = UIColor.White.CGColor;
			DescrptionTextView.Layer.BorderColor = UIColor.Gray.CGColor;
			DescrptionTextView.Layer.BorderWidth = 0.5f;
			DescrptionTextView.Layer.CornerRadius = 6.0f;
			DescrptionTextView.Layer.MasksToBounds = true;
		}
	}
}