// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using MvvmCross.Binding.BindingContext;
using MvvmCross.Platforms.Ios.Binding.Views;
using MvvmCross.Platforms.Ios.Presenters.Attributes;
using MvvmCross.Platforms.Ios.Views;
using UIKit;

namespace TodoApp.iOS.Views
{
	[MvxFromStoryboard]
	[MvxChildPresentation]
	public partial class ListInfoView : MvxTableViewController
	{
		public ListInfoView(IntPtr handle)
			: base(handle)
		{
		}

		public override void ViewDidLoad()
		{
			base.ViewDidLoad();

			var options = new UIBarButtonItem(UIBarButtonSystemItem.Action);
			var add = new UIBarButtonItem(UIBarButtonSystemItem.Add);

			this.NavigationItem.RightBarButtonItems = new UIBarButtonItem[] { options, add };

			var source = new MvxStandardTableViewSource(this.TableView, "TitleText Title;");
			TableView.Source = source;

			var set = this.CreateBindingSet<ListInfoView, ViewModels.ListInfoViewModel>();
			set.Bind(source)
			   .For(x => x.ItemsSource)
			   .To(vm => vm.Items);
			set.Bind(NavigationItem)
			   .For(x => x.Title)
			   .To(vm => vm.Title);
			set.Bind(add)
			   .To(vm => vm.AddNewItem);
			set.Bind(options)
			   .To(vm => vm.ShowOptions);
			set.Apply();
		}
	}
}